name: "bug report"
description: "Bug report for github issues"
title: "[Ошибка]:"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание ошибки"
      placeholder: "Опишите ошибку"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Шаги воспроизведения ошибки"
      placeholder: "Опишите шаги для воспроизведения ошибки"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемый результат"
      placeholder: "Опишите что должно было произойит"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Фактический результат"
      placeholder: "Опищите реальное поведение программы"
    validations:
      required: true
  - type: textarea
    id: additions
    attributes:
      label: "Дополнительные материалы"
      placeholder: "Прикрепите скриншоты и файлы здесь"
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: "Среда выполнения"
      options:
        - Windows 11
        - Windows 10
        - MacOS
        - Ubuntu
        - Unix
        - Android 
        - iOS 
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      options:
        - Высокий
        - Средний
        - Низкий
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: "Серьёзность"
      options:
        - Высокая
        - Средняя
        - Низкая
        - Критическая
    validations:
      required: true
