name: PractWork3
description: bug report template for PractWork3
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Шаги воспроизведения
      description: поле для ввда шагов для воспроизведения бага
      placeholder: Введите шаги для воспроизведения бага
    validations:
      required: true 
- type: textarea
    id: reproduction-steps
    attributes:
      label: expected-result
      description: поле для ввоад ожидаемых результатов
      placeholder: Введите ожидаемый результат
    validations:
      required: true 
- type: dropdown
    id: идентификатор поля ввода
    attributes:
      label: подпись поля
      description: описание
      options:
       - список
       - опций
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Отобразить текст с разметкой markdown
  - type: checkboxes
    id: идентификатор поля ввода
    attributes:
      label: подпись
      description: описание
      options:
      - label: флажок 1
        required: true #флажок обязателен или нет
