name: PractWork3
description: bug report template for PractWork3
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Шаги воспроизведения
      description: Поле для ввда шагов для воспроизведения бага
      placeholder: Введите шаги для воспроизведения бага
    validations:
      required: true 
- type: textarea
    id: expected-result
    attributes:
      label: Ожидаемый результат
      description: Поле для ввоад ожидаемых результатов
      placeholder: Введите ожидаемый результат
    validations:
      required: true 
- type: textarea
    id: actual-result
    attributes:
      label: Фактический результат
      description: Поле для ввоад фактических результатов
      placeholder: Введите фактический результат
    validations:
      required: true 
- type: textarea
    id: additional-materials
    attributes:
      label: Дополнительные материалы и скриншоты
      description: Поле для размещения дополнительных материалов 
      placeholder: разместите дополнительные материалы
    validations:
      required: false
- type: dropdown
    id: идентификатор поля ввода
    attributes:
      label: подпись поля
      description: описание
      options:
       - список
       - опций
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Отобразить текст с разметкой markdown
  - type: checkboxes
    id: идентификатор поля ввода
    attributes:
      label: подпись
      description: описание
      options:
      - label: флажок 1
        required: true #флажок обязателен или нет
